version: "3.8"
services:
  payment:
    build: .
    depends_on:
      - db
    ports:
      - 2801:2801
  db:
    image: postgres:14.1-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: link
